name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true

      - name: Update version in code
        run: |
          sed -i 's/version = \["SNAPSHOT"\]/version = ["${{ github.ref_name }}"]/g' src/main/kotlin/com/hightouchinc/WireguardManagerCommand.kt

      - name: Run tests
        run: ./gradlew test --build-cache --parallel
        env:
          VERSION: ${{ github.ref_name }}

      - name: Build Shadow JAR
        run: ./gradlew shadowjar --build-cache
        env:
          VERSION: ${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: build/libs/wireguard-manager-*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}